name: Build and Push Golang Docker Image

# Trigger the workflow on push to the main branch or pull requests
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_IMAGE_TAG: 2024100901
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        env:
          GOLANG_TAG: 1.19-bullseye
        run: |
          docker build --build-arg GOLANG_TAG=$GOLANG_TAG -t ghcr.io/${{ github.repository }}/ci-go-image:$CI_IMAGE_TAG .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/ci-go-image:$CI_IMAGE_TAG